spring:
  application:
    name: 'loja'

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: 'http://localhost:8761/eureka'

feign:
  client: 
    config: 
      default:
         connectTimeout: 80000000
         readTimeout: 80000000